### ISSUE TITLE
ClassCastException on class org.eclipse.jdt.internal.core.JavaNature

### ISSUE THREAD

**Issue by Kiiv** [eclipse-jeetools/webtools.javaee#10]
Hi,

after upgrading to Eclipse 2024-03, i've got a lot of error of this kind :

```
Stacktrace :

java.lang.ClassCastException: class org.eclipse.jdt.internal.core.JavaNature cannot be cast to class org.eclipse.jdt.core.IJavaProject (org.eclipse.jdt.internal.core.JavaNature and org.eclipse.jdt.core.IJavaProject are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @69dcf047)
	at org.eclipse.jem.workbench.utility.JemProjectUtilities.getJavaProject(JemProjectUtilities.java:203)
	at org.eclipse.jst.j2ee.internal.validation.ProjectValidationHelper.getCachedOutputContainers(ProjectValidationHelper.java:44)
	at org.eclipse.jst.j2ee.internal.validation.ProjectValidationHelper.getOutputContainers(ProjectValidationHelper.java:63)
	at org.eclipse.wst.validation.internal.ValidatorMetaData.checkIfValidSourceFile(ValidatorMetaData.java:344)
	at org.eclipse.wst.validation.internal.ValidatorMetaData.isApplicableTo(ValidatorMetaData.java:315)
	at org.eclipse.wst.validation.internal.ValidatorMetaData.isApplicableTo(ValidatorMetaData.java:306)
	at org.eclipse.wst.validation.internal.FilterUtil.filterOut(FilterUtil.java:339)
	at org.eclipse.wst.validation.internal.FilterUtil.filterOut(FilterUtil.java:376)
	at org.eclipse.wst.validation.internal.FilterUtil.filterOut(FilterUtil.java:433)
	at org.eclipse.wst.validation.internal.FilterUtil$2.visit(FilterUtil.java:631)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:87)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:87)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:87)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:87)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:66)
	at org.eclipse.wst.validation.internal.FilterUtil.loadDeltas(FilterUtil.java:647)
	at org.eclipse.wst.validation.internal.operations.ValidationOperation.loadFileDeltas(ValidationOperation.java:547)
	at org.eclipse.wst.validation.internal.operations.ValidationOperation.getFileDeltas(ValidationOperation.java:519)
	at org.eclipse.wst.validation.internal.operations.ValidationOperation.preValidate(ValidationOperation.java:791)
	at org.eclipse.wst.validation.internal.operations.ValidationOperation.run(ValidationOperation.java:653)
	at org.eclipse.wst.validation.internal.operations.ValidationBuilder.build(ValidationBuilder.java:192)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1077)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Session Data :
eclipse.buildId=4.31.0.20240307-1200
java.version=17.0.10
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=fr_FR
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

```

Any idea of the root cause ? Didn't install anything else between and I've keep my previous workspace.

Here is the details of installation :
```
  Bndtools	7.0.0.REL-202310060912-gb82dc86	bndtools.main.feature.feature.group	Bndtools
  Bndtools m2e	7.0.0.REL-202310060912-gb82dc86	bndtools.m2e.feature.feature.group	Bndtools
  Buildship: Eclipse Plug-ins for Gradle	3.1.9.v20240115-1636	org.eclipse.buildship.feature.group	Eclipse Buildship
  Bytecode Outline View	1.2.300.v20240118-1157	org.eclipse.jdt.bcoview.feature.feature.group	Eclipse.org
  Checkstyle configuration plugin for M2Eclipse	2.1.0.202312161747-r	com.basistech.m2e.code.quality.checkstyle.feature.feature.group	null
  Debug Adapter client for Eclipse IDE (Incubation)	0.15.7.202402141138	org.eclipse.lsp4e.debug	null
  DevStyle (includes Darkest Dark Theme)	2024.1.0.202401312140	com.genuitec.eclipse.theming.core.feature.feature.group	CodeTogether Inc.
  EclEmma Java Code Coverage	3.1.8.202312121452	org.eclipse.eclemma.feature.feature.group	Eclipse EclEmma
  Eclipse IDE for Java Developers	4.31.0.20240307-1200	epp.package.java	Eclipse Packaging Project
  Eclipse Java Development Tools	3.19.400.v20240229-0520	org.eclipse.jdt.feature.group	Eclipse.org
  Extra Syntax Highlighting	1.0.0.20240311-2026	de.sebthom.eclipse.extra_syntax_highlighting.feature.feature.group	Sebastian Thomschke
  Git integration for Eclipse	6.9.0.202403050737-r	org.eclipse.egit.feature.group	Eclipse EGit
  GWT 2.8.2 SDK	2.8.0.202305162146	com.gwtplugins.eclipse.sdkbundle.gwt28.feature.feature.group	GWT Eclipse Plugin
  GWT Eclipse Plugin	4.0.1.202305162146	com.gwtplugins.eclipse.suite.v3.feature.feature.group	GWT Eclipse Plugin
  Java implementation of Git	6.9.0.202403050737-r	org.eclipse.jgit.feature.group	Eclipse JGit
  JNA Library	4.1.0.v06022015_1911	net.java.dev.jna.feature.group	null
  JustJ JRE for IDE Packages	17.0.0.v20240120-1430	org.eclipse.justj.epp.feature.group	Eclipse JustJ
  Language Server Protocol client for Eclipse IDE (Incubation)	0.18.6.202403050753	org.eclipse.lsp4e	Eclipse.org
  M2E - Maven Integration for Eclipse	2.6.0.20240220-1109	org.eclipse.m2e.feature.feature.group	Eclipse.org - m2e
  M2E - POM Editor using LemMinX language server (includes Incubating components)	2.0.600.20240219-1707	org.eclipse.m2e.lemminx.feature.feature.group	Eclipse.org - m2e
  M2E - SLF4J over Logback Logging	2.6.0.20240217-1525	org.eclipse.m2e.logback.feature.feature.group	Eclipse.org - m2e
  Marketplace Client	1.10.3.v20240228-1000	org.eclipse.epp.mpc.feature.group	Eclipse Marketplace Client
  Mylyn WikiText	4.2.0.v20240302-0923	org.eclipse.mylyn.wikitext.feature.feature.group	Eclipse Mylyn
  Oomph Setup	1.31.0.v20240306-1109	org.eclipse.oomph.setup.feature.group	Eclipse Oomph Project
  PyDev for Eclipse	12.0.0.202402031810	org.python.pydev.feature.feature.group	Fabio Zadrozny
  SonarLint for Eclipse	10.0.1.81733	org.sonarlint.eclipse.feature.feature.group	SonarSource
  Source Map Editor Feature	2.1.0.202303101717	com.github.sdbg.feature.feature.group	null
  SQL Editor	1.4.0	de.jcup.sqleditor.feature.group	Albert Tregnaghi
  Subversive SVN Connectors	6.0.4.I20161211-1700	org.polarion.eclipse.team.svn.connector.feature.group	Polarion Software
  Subversive SVN Integration for the M2E Project (Optional)	4.9.0.v20231006-0856	org.eclipse.team.svn.m2e.feature.group	Eclipse.org
  Subversive SVN Team Provider	4.9.0.v20231006-0856	org.eclipse.team.svn.feature.group	Eclipse.org
  Subversive SVN Team Provider Core	4.9.0.v20231006-0856	org.eclipse.team.svn.core.feature.group	Eclipse.org
  Subversive SVN Team Provider UI Capabilities	4.0.0.v20231006-0856	org.eclipse.team.svn.ui.capabilities.feature.group	Eclipse.org
  SVNKit 1.10.x Implementation (Optional)	6.1.0	org.polarion.eclipse.team.svn.connector.svnkit1_10.feature.group	osspit.org
  SVNKit Library	1.10.6.r10830	org.tmatesoft.svnkit.feature.group	TMate Software
  TextMate Core	0.11.1.202403141146	org.eclipse.tm4e.feature.feature.group	Eclipse TM4E
  TextMate Language Pack	0.11.1.202403141146	org.eclipse.tm4e.language_pack.feature.feature.group	Eclipse TM4E
  Tip of the Day UI Feature	0.4.300.v20240207-1044	org.eclipse.tips.feature.feature.group	Eclipse.org
  TM Terminal	11.5.0.202312062348	org.eclipse.tm.terminal.feature.feature.group	Eclipse CDT
  Tycho Project Configurators	0.10.0.20220926-1324	org.sonatype.tycho.m2e.feature.feature.group	Sonatype, Inc.
  Wild Web Developer HTML, CSS, JSON, Yaml, JavaScript, TypeScript, Node tools	1.3.4.202402150151	org.eclipse.wildwebdeveloper.feature.feature.group	Eclipse Wild Web Developer project
  Wild Web Developer XML tools	1.3.2.202312212027	org.eclipse.wildwebdeveloper.xml.feature.feature.group	Eclipse Wild Web Developer project
```

**Comment by erik-brangs** [comment]
The problem you're reporting should have been fixed by https://github.com/eclipse-jeetools/webtools.javaee/commit/22927bb365025cf747d1094c2a34b28232bf0190 which was part of the official release for 2024-03.

What's the version of the plugin `org.eclipse.jem.workbench` in your installation? It should be `org.eclipse.jem.workbench_2.1.100.v202402230230.jar` for 2024-03.

I suspect something went wrong with your upgrade to 2024-03 and WTP did not get upgraded to the correct versions.

**Comment by Kiiv** [comment]
Dammit, I'm on :
	Eclipse.org	Java EMF Model Workbench Support	2.1.0.v202101081429	org.eclipse.jem.workbench

Do you now if there is a way to repair this ? there is nothing when I check for updates.

**Comment by nitind** [comment]
The "Eclipse Java Web Development Core" feature that usually contains that plug-in, and has the newer version, pulls in functionality you don't necessarily want. Can you check if any of the `feature.xml` files under your `eclipse/features` directory already references this plug-in?

**Comment by Kiiv** [comment]
Hi !

```
~/eclipse/features$ grep -R org.eclipse.jem.workbench .
```
does not return anything

**Comment by nitind** [comment]
That's a shame, but it does provide a possible reason the plug-in didn't get updated. Intentionally installing "Eclipse Java Web Development Core" from the latest release site might clear things up.

**Comment by Kiiv** [comment]
You're right, installing "Eclipse Java Web Development Core" did the trick but I don't know if I really need it in my life :)

Anyway, I will survive with this solution at the moment ;)
Thanks !
